Distributor/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using static Distributor.Enums.EntityEnums;

namespace Distributor.Models
{
    public class Campaign
    {
        [Key]
        public Guid CampaignId { get; set; }

        [Display(Name="Campaign name")]
        public string Name { get; set; }

        [Display(Name = "Campaign strapline")]
        public string StrapLine { get; set; }

        [Display(Name = "Campaign description")]
        public string Description { get; set; }

        [Display(Name = "Poster/image")]
        public byte[] Image { get; set; }

        [Display(Name = "Poster/image location")]
        public string ImageLocation { get; set; }

        [Display(Name = "Website")]
        public string Website { get; set; }

        [Display(Name = "Campaign start date/time")]
        public DateTime? CampaignStartDateTime { get; set; }

        [Display(Name = "Campaign end date/time")]
        public DateTime? CampaignEndDateTime { get; set; }

        [Display(Name = "Location name")]
        public string LocationName { get; set; }

        [Display(Name = "Address line 1")]
        public string LocationAddressLine1 { get; set; }

        [Display(Name = "Address line 2")]
        public string LocationAddressLine2 { get; set; }

        [Display(Name = "Address line 3")]
        public string LocationAddressLine3 { get; set; }

        [Display(Name = "Address town/city")]
        public string LocationAddressTownCity { get; set; }

        [Display(Name = "Address county")]
        public string LocationAddressCounty { get; set; }

        [Required]
        [Display(Name = "Address postcode")]
        public string LocationAddressPostcode { get; set; }

        [Display(Name = "Telephone number")]
        public string LocationTelephoneNumber { get; set; }

        [Display(Name = "Email")]
        public string LocationEmail { get; set; }

        [Display(Name = "Contact name")]
        public string LocationContactName { get; set; }

        [Display(Name = "Status")]
        public EntityStatusEnum EntityStatus { get; set; }

        //references to the listing originator
        public Guid CampaignOriginatorAppUserId { get; set; }
        public Guid CampaignOriginatorBranchId { get; set; }
        public Guid CampaignOriginatorCompanyId { get; set; }
        public DateTime CampaignOriginatorDateTime { get; set; }
    }
}

Distributor/ViewModels/CampaignViews.cs
using Distributor.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using static Distributor.Enums.EntityEnums;

namespace Distributor.ViewModels
{
    public class CampaignAddView : CallingFields
    {
        [Display(Name = "Campaign name")]
        public string Name { get; set; }

        [Display(Name = "Campaign strapline")]
        public string StrapLine { get; set; }

        [Display(Name = "Campaign description")]
        public string Description { get; set; }

        [Display(Name = "Poster/image")]
        public byte[] Image { get; set; }

        [Display(Name = "Poster/image location")]
        public string ImageLocation { get; set; }

        [Display(Name = "Website")]
        public string Website { get; set; }

        [Display(Name = "Campaign start date/time")]
        public DateTime? CampaignStartDateTime { get; set; }

        [Display(Name = "Campaign end date/time")]
        public DateTime? CampaignEndDateTime { get; set; }

        [Display(Name = "Location name")]
        public string LocationName { get; set; }

        [Display(Name = "Address line 1")]
        public string LocationAddressLine1 { get; set; }

        [Display(Name = "Address line 2")]
        public string LocationAddressLine2 { get; set; }

        [Display(Name = "Address line 3")]
        public string LocationAddressLine3 { get; set; }

        [Display(Name = "Address town/city")]
        public string LocationAddressTownCity { get; set; }

        [Display(Name = "Address county")]
        public string LocationAddressCounty { get; set; }

        [Display(Name = "Address postcode")]
        public string LocationAddressPostcode { get; set; }

        [Display(Name = "Telephone number")]
        public string LocationTelephoneNumber { get; set; }

        [Display(Name = "Email")]
        public string LocationEmail { get; set; }

        [Display(Name = "Contact name")]
        public string LocationContactName { get; set; }
    }

    public class CampaignGeneralInfoView : BlocksAndOwners
    {
        public Campaign Campaign { get; set; }
    }

    public class CampaignManageView
    {
        public Campaign Campaign { get; set; }
    }

    public class CampaignEditView
    {
        public Guid CampaignId { get; set; }

        [Display(Name = "Campaign name")]
        public string Name { get; set; }

        [Display(Name = "Campaign strapline")]
        public string StrapLine { get; set; }

        [Display(Name = "Campaign description")]
        public string Description { get; set; }

        [Display(Name = "Poster/image")]
        public byte[] Image { get; set; }

        [Display(Name = "Poster/image location")]
        public string ImageLocation { get; set; }

        [Display(Name = "Website")]
        public string Website { get; set; }

        [Display(Name = "Campaign start date/time")]
        public DateTime? CampaignStartDateTime { get; set; }

        [Display(Name = "Campaign end date/time")]
        public DateTime? CampaignEndDateTime { get; set; }

        [Display(Name = "Location name")]
        public string LocationName { get; set; }

        [Display(Name = "Address line 1")]
        public string LocationAddressLine1 { get; set; }

        [Display(Name = "Address line 2")]
        public string LocationAddressLine2 { get; set; }

        [Display(Name = "Address line 3")]
        public string LocationAddressLine3 { get; set; }

        [Display(Name = "Address town/city")]
        public string LocationAddressTownCity { get; set; }

        [Display(Name = "Address county")]
        public string LocationAddressCounty { get; set; }

        [Required]
        [Display(Name = "Address postcode")]
        public string LocationAddressPostcode { get; set; }

        [Display(Name = "Telephone number")]
        public string LocationTelephoneNumber { get; set; }

        [Display(Name = "Email")]
        public string LocationEmail { get; set; }

        [Display(Name = "Contact name")]
        public string LocationContactName { get; set; }

        [Display(Name = "Status")]
        public EntityStatusEnum EntityStatus { get; set; }

        //references to the listing originator
        public DateTime CampaignOriginatorDateTime { get; set; }
        public AppUser CampaignAppUser { get; set; }
        public Branch CampaignBranchDetails { get; set; }
        public Company CampaignCompanyDetails { get; set; }

        public ViewButtons Buttons { get; set; }
    }
}

Distributor/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Distributor.Models;
using Distributor.Helpers;
using Distributor.ViewModels;
using System.IO;

namespace Distributor.Controllers
{
    [Authorize]
    public class CampaignsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //// GET: Campaigns
        //public ActionResult Index()
        //{
        //    return View(db.Campaigns.ToList());
        //}

        // GET: Campaigns/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CampaignEditView campaign = CampaignEditHelpers.GetCampaignEditView(db, id.Value, User);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // GET: Campaigns/Create
        public ActionResult Create()
        {
            string callingController = "Home";
            string callingAction = "Index";

            try
            {
                string[] callingUrlSegments = Request.UrlReferrer.Segments.Select(x => x.TrimEnd('/')).ToArray();
                callingController = callingUrlSegments[callingUrlSegments.Count() - 2];
                callingAction = callingUrlSegments[callingUrlSegments.Count() - 1];
            }
            catch { }

            ViewBag.CallingController = callingController;

            CampaignAddView model = new CampaignAddView()
            {
                CallingAction = callingAction,
                CallingController = callingController
            };

            return View(model);
        }

        // POST: Campaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,StrapLine,Description,Image,ImageLocation,Website,CampaignStartDateTime,CampaignEndDateTime,LocationName,LocationAddressLine1,LocationAddressLine2,LocationAddressLine3,LocationAddressTownCity,LocationAddressCounty,LocationAddressPostcode,LocationTelephoneNumber,LocationEmail,LocationContactName,CallingAction,CallingController")] CampaignAddView campaign, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/images"), pic);
                    // file is uploaded
                    //file.SaveAs(path);

                    //campaign.ImageLocation = path;

                    // save the image path path to the database or you can send image 
                    // directly to database
                    // in-case if you want to store byte[] ie. for DB
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();

                        campaign.Image = array;
                    }

                }

                CampaignHelpers.CreateCampaignFromCampaignAddView(campaign, User);
                
                return RedirectToAction(campaign.CallingAction, campaign.CallingController);
            }

            return View(campaign);
        }

        // GET: Campaigns/Edit/5
        public ActionResult Edit(Guid? id, bool showHistory)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CampaignEditView campaign = CampaignEditHelpers.GetCampaignEditView(db, id.Value, User);
            if (campaign == null)
            {
                return HttpNotFound();
            }

            ViewBag.ShowHistory = showHistory;

            return View(campaign);
        }

        // POST: Campaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CampaignId,Name,StrapLine,Description,Image,ImageLocation,Website,CampaignStartDateTime,CampaignEndDateTime,LocationName,LocationAddressLine1,LocationAddressLine2,LocationAddressLine3,LocationAddressTownCity,LocationAddressCounty,LocationAddressPostcode,LocationTelephoneNumber,LocationEmail,LocationContactName,EntityStatus")]CampaignEditView campaign)
        {
            if (ModelState.IsValid)
            {
                //If the 'Submit' button pressed then update tables, else leave as are so that on reload it takes original values once again.
                if (Request.Form["submitbutton"] != null)
                {
                    //Update tables
                    CampaignHelpers.UpdateCampaignFromCampaignEditView(db, campaign);

                    return RedirectToAction("Campaigns", "ManageListings");
                }

                return RedirectToAction("Edit");
            }

            //rebuild the missing details before returning to screen to show errors
            Campaign campaignDetails = CampaignHelpers.GetCampaign(db, campaign.CampaignId);
            campaign.CampaignAppUser = AppUserHelpers.GetAppUser(db, campaignDetails.CampaignOriginatorAppUserId);
            campaign.CampaignBranchDetails = BranchHelpers.GetBranch(db, campaignDetails.CampaignOriginatorBranchId);

            return View(campaign);
        }

        //// GET: Campaigns/Delete/5
        //public ActionResult Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Campaign campaign = db.Campaigns.Find(id);
        //    if (campaign == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(campaign);
        //}

        //// POST: Campaigns/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(Guid id)
        //{
        //    Campaign campaign = db.Campaigns.Find(id);
        //    db.Campaigns.Remove(campaign);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public ActionResult History()
        {
            List<CampaignManageView> model = CampaignManageHelpers.GetAllCampaignsManageView(User, true);
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Distributor/Controllers/GeneralInfoController.cs
using Distributor.Helpers;
using Distributor.Models;
using Distributor.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Distributor.Controllers
{
    [Authorize]
    public class GeneralInfoController : Controller
    {   
        public ActionResult Requirements()
        {
            List<RequirementListingGeneralInfoView> model = RequirementListingGeneralInfoHelpers.GetAllRequirementListingsGeneralInfoView(User);

            Company userCompany = CompanyHelpers.GetCompanyForUser(User);
            ViewBag.CurrentCompanyId = userCompany.CompanyId;

            return View(model);
        }

        public ActionResult Available()
        {
            List<AvailableListingGeneralInfoView> model = AvailableListingGeneralInfoHelpers.GetAllAvailableListingsGeneralInfoView(User);

            Company userCompany = CompanyHelpers.GetCompanyForUser(User);
            ViewBag.CurrentCompanyId = userCompany.CompanyId;

            return View(model);
        }

        public ActionResult Campaigns()
        {
            List<CampaignGeneralInfoView> model = CampaignGeneralInfoViewHelpers.GetAllCampaignsGeneralInfoView(User);

            //Do any filtering

            return View(model);
        }
    }
}

Distributor/Views/GeneralInfo/Campaigns.cshtml
@model IEnumerable<Distributor.ViewModels.CampaignGeneralInfoView>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/css/vendor")
    @*<script type="text/javascript" src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>*@
}

<nav class="navbar navbar-fixed-top">
    <div class="navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Distributor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="#">Brand</a>*@
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="disabled">@Html.ActionLink("GENERAL INFO", "General", "Home")</li>
                    <li>@Html.ActionLink("Requests", "Requirements", "GeneralInfo")</li>
                    <li>@Html.ActionLink("Available", "Available", "GeneralInfo")</li>
                    <li class="active">@Html.ActionLink("Campaigns", "Campaigns", "GeneralInfo")</li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
</nav>

<div class="row" style="padding-top:55px">
    <div class="col-lg-12">
        <h1 class="page-header" style="margin: 10px 0px 10px">General Info <small>Campaigns</small></h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Campaigns</li>
        </ol>
        <p class="lead">Current campaigns.</p>
    </div>
</div>

<div class="table-responsive">
    @if (Model.Count() == 0)
    {
        <p>No details to show</p>
    }
    else
    {
        <table id="campaignTable" class="table table-hover">
            <thead>
                <tr class="info">
                    <th>Name</th>
                    <th>StrapLine</th>
                    <th>Description</th>
                    <th>Website</th>
                    <th>Start date/time</th>
                    <th>End date/time</th>
                </tr>
            </thead>

            <tbody>@foreach (var item in Model)
            {
                if (item.CompanyLevelBlock && item.DisplayBlocks)
                {
                    <tr style="color:darkred">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if (item.BranchLevelBlock && item.DisplayBlocks)
                {
                    <tr style="color:indianred">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if (item.UserLevelBlock && item.DisplayBlocks)
                {
                    <tr style="color:red">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if ((item.CompanyLevelBlock || item.BranchLevelBlock || item.UserLevelBlock) && !item.DisplayBlocks)
                {
                    //do nothing, don't show the row
                }
                else if (item.UserLevelOwner && item.DisplayMyRecords)
                {
                    <tr style="color:green">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if (item.UserLevelOwner && !item.DisplayMyRecords)
                {
                    //do nothing, don't show the row
                }
                else if (item.BranchLevelOwner && item.DisplayMyBranchRecords)
                {
                    <tr style="color:forestgreen">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if (item.BranchLevelOwner && !item.DisplayMyBranchRecords)
                {
                    //do nothing, don't show the row
                }
                else if (item.CompanyLevelOwner && item.DisplayMyCompanyRecords)
                {
                    <tr style="color:darkgreen">
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
                else if (item.CompanyLevelOwner && !item.DisplayMyCompanyRecords)
                {
                    //do nothing, don't show the row
                }
                else
                {
                    <tr>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Name)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.StrapLine)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Description)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.Website)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignStartDateTime)</td>
                        <td onclick="location.href='@Url.Action("Details", "Campaigns", new { id = item.Campaign.CampaignId })'">@Html.DisplayFor(modelItem => item.Campaign.CampaignEndDateTime)</td>
                    </tr>
                }
            }
            </tbody>

        </table>
    }
</div>

<div class="form-group">
    @Html.ActionLink("Add campaign", "Create", "Campaigns", "", new { @class = "btn btn-primary" })
</div>