Distributor/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using static Distributor.Enums.GeneralEnums;
using static Distributor.Enums.GroupEnums;

namespace Distributor.Models
{
    public class Group
    {
        [Key]
        public Guid GroupId { get; set; }

        [Required]
        [Display(Name = "Group name")]
        public string Name { get; set; }

        [Display(Name = "Type of group")]
        public LevelEnum Type { get; set; }

        [Display(Name = "Group visibility")]
        public GroupVisibilityEnum VisibilityLevel { get; set; }

        [Display(Name = "Group invite level")]
        public GroupInviteLevelEnum InviteLevel { get; set; }

        [Display(Name = "Group invite acceptance level")]
        public GroupInviteAcceptanceLevelEnum AcceptanceLevel { get; set; }

        //references to the listing originator
        public Guid GroupOriginatorAppUserId { get; set; }
        public DateTime GroupOriginatorDateTime { get; set; }
    }
}

Distributor/ViewModels/GroupViews.cs
using Distributor.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using static Distributor.Enums.GeneralEnums;
using static Distributor.Enums.GroupEnums;

namespace Distributor.ViewModels
{
    public class GroupListView
    {
        public Group Group { get; set; }
        public string GroupOriginatorName { get; set; }
        //public List<GroupMember> Members { get; set; }
        public List<GroupMemberListView> Members { get; set; }
    }

    public class GroupMemberListView
    {
        public GroupMember GroupMember { get; set; }
        public string GroupMemberName { get; set; } //this could be user, branch, company
    }

    public class GroupEditView
    {
        public List<GroupListView> GroupListViewsCreatedByUser { get; set; }
        public List<GroupListView> GroupListViewsRelevantToUser { get; set; }
    }


    public class GroupAddView
    {
        [Required]
        [Display(Name = "Group name")]
        public string Name { get; set; }

        [Display(Name = "Type of group")]
        public LevelEnum Type { get; set; }

        [Display(Name = "Group visibility")]
        public GroupVisibilityEnum VisibilityLevel { get; set; }

        [Display(Name = "Group invite level")]
        public GroupInviteLevelEnum InviteLevel { get; set; }

        [Display(Name = "Group invite acceptance level")]
        public GroupInviteAcceptanceLevelEnum AcceptanceLevel { get; set; }

        public bool scratchEntry { get; set; }

        public List<GroupAddMemberView> Members { get; set; }
    }

    public class GroupAddMemberView
    {
        [Display(Name = "Selected")]
        public bool SelectedUser { get; set; }

        public Guid ReferenceId { get; set; }

        [Display(Name = "Name")]
        public string ReferenceName { get; set; }
    }
}

Distributor/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Distributor.Models;
using Distributor.Helpers;
using Distributor.ViewModels;
using static Distributor.Enums.GeneralEnums;

namespace Distributor.Controllers
{
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        public ActionResult Index()
        {
            GroupEditView model = GroupViewHelpers.GetGroupEditViewForUser(db, AppUserHelpers.GetAppUserIdFromUser(User));
            return View(model);

            //This view will do everything.
            //List all groups you belong to
            //List all your 'friends' groups
            //List the 'requests' to join your group for approval
            //Allow you to 'add' a new group
            //Allow you to remove 'your' group (you are group admin)
            //Allow you to 'request' a friend join your group (on them saying yes it automatically adds them)
            //Allow you to 'join' a friends group (on them saying yes it automatically adds you)

            //PS Need to add the 'friend request' stuff also. - i.e.
            //Friend table that holds type (User, branch, company) and Id.
            //- on company admin it will show company friends and give 'admin' the ability to add/remove etc..
            //- on branch admin it will show branch friends and give 'admin' & 'manager' the ability to add/remove etc.
            //- on user it will show user friends and give all ability to add/remove etc..
            //.....therefore 'add friend' on listings page highlighting company/branch/user need to be displayed for those with right access.
            //.....this will then go off for approval
        }

        // GET: Groups/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        //first 4 variables come from the +Button on the general info screens.
        public ActionResult Create(LevelEnum? level, Guid? ofReferenceId, Guid? byReferenceId, Guid? byAppUserId, Guid? appUserId)
        {
            if (appUserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            GroupAddView model = GroupViewHelpers.GetGroupAddView(level, ofReferenceId, byReferenceId, byAppUserId, appUserId.Value);

            return View(model);
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupAddView model)
        {
            if (ModelState.IsValid)
            {
                GroupHelpers.CreateGroupFromGroupAddView(db, model, User);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult GetMemberList(string groupName, string memberType)
        {
            GroupAddView model = GroupViewHelpers.GetGroupAddView(groupName, memberType, User);

            return PartialView("AddGroupMembers", model);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupId,Name,GroupOriginatorAppUserId,GroupOriginatorDateTime")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Distributor/Views/Groups/AddGroupMembers.cshtml
@model Distributor.ViewModels.GroupAddView


@for(int i = 0; i < Model.Members.Count; i++)
{
    @Html.HiddenFor(m => m.Members[i].ReferenceName)
    @Html.HiddenFor(m => m.Members[i].ReferenceId)
    <tr>
        <td>@Html.CheckBoxFor(m => m.Members[i].SelectedUser)</td>
        <td>@Html.DisplayFor(m => m.Members[i].ReferenceName)</td>
    </tr>
}

Distributor/Views/Groups/Create - Copy.cshtml
@using Distributor.Extenstions;

@model Distributor.ViewModels.GroupAddView

@{
    var currentAppUserId = User.Identity.GetAppUserId();
    var rowId = Guid.Empty;
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/css/vendor")

    <script type="text/javascript">
        //This will hide/display company details depending if the company has been selected or not
        function GetUserList() {
            var userTable = document.getElementById("usertable");
            userTable.style.display = "block";

            var url = "/Data/GetUserList";

            $.ajax({
                url: url,
                data: {  },
                cache: false,
                type: "POST",
                success: function (data) {
                    //$('#usertablelist').append(data.html);
                    for (var i in data) {
                        alert(data[i].users.AppUserId.toString());
                    }
                },
                error: function (response) {
                    alert("error : " + response);
                }
            });
        };

        function GetListForType(typeDropDownValueId, calledFromFormLoad) {
            var typeDropDownValue = $("#typedropdown option:selected").text();
            switch (typeDropDownValue) {
                case "Company":
                    GetCompanyList();
                    break;
                case "Branch":
                    GetBranchList();
                    break;
                case "User":
                    GetUserList();
                    break;
            }
        };
                
        $(document).ready(function () {
            var typeDropDownValueId = $("#typedropdown option:selected").val();
            var typeDropDownValue = $("#typedropdown option:selected").text();
            GetListForType(typeDropDownValueId, true);  //set to true as this is called when form loads
        });
    </script>
}




<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="margin: 10px 0px 10px">
            Add group
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("User changes", "Edit", "AppUsers", new { id = currentAppUserId }, "")</li>
            <li>@Html.ActionLink("Your groups", "Index", "Groups")</li>
            <li class="active">Add group</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="row">
        <div class="col-md-6">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <h4>Group details</h4>

                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*NOTE: The if statement to stop a field being changeable if it comes from the buttons and details are pre-loaded*@
                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @if (Model.scratchEntry)
                        {
                            @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control", @id = "typedropdown", onchange = "javascipt:GetListForType(this.value);" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @id = "typedropdown" } })
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Add members</h4>
            <div id="usertable" style="display:none">
                <div class="table-responsive">
                    <table class="table table-hover" id="usertablelist">
                        <tr class="info">
                            <th>Select</th>
                            <th>User name</th>
                            <th></th>
                        </tr>
                    </table>
                </div>
            </div>
            <div id="branchtable" style="display:none">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tr class="info">
                            <th>Select</th>
                            <th>Branch name</th>
                        </tr>
                    </table>
                </div>
            </div>
            <div id="companytable" style="display:none">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <tr class="info">
                            <th>Select</th>
                            <th>Company name</th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-success" />
    </div>
}

Distributor/Views/Groups/Create.cshtml
@using Distributor.Extenstions;

@model Distributor.ViewModels.GroupAddView

@{
    var currentAppUserId = User.Identity.GetAppUserId();
    var rowId = Guid.Empty;
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/css/vendor")

    <script type="text/javascript">
        function GetListForType(typeDropDownValueId) {
            var typeDropDownValue = $("#typedropdown option:selected").text();
            var groupName = $("#groupname").val();

            switch (typeDropDownValue) {
                case "Company":
                    @*$("#memberlist").load('@(Url.Action("GetMemberList", "Groups"))?groupName=' + groupName + '&memberType=Company');*@
                    var url = "/Groups/GetMemberList/?groupName=" + groupName + "&memberType=Company";
                    $("#memberlist").load(url);
                    break;
                case "Branch":
                    @*$("#memberlist").load('@(Url.Action("GetMemberList", "Groups"))?groupName=' + groupName + '&memberType=Branch');*@
                    var url = "/Groups/GetMemberList/?groupName=" + groupName + "&memberType=Branch";
                    $("#memberlist").load(url);
                    break;
                case "User":
                    @*$("#memberlist").load('@(Url.Action("GetMemberList", "Groups"))?groupName=' + groupName + '&memberType=User');*@
                    var url = "/Groups/GetMemberList/?groupName=" + groupName + "&memberType=User";
                    $("#memberlist").load(url);
                    break;
            }
        };

        //$(document).ready(function () {
        //    var typeDropDownValueId = $("#typedropdown option:selected").val();
        //    var typeDropDownValue = $("#typedropdown option:selected").text();
        //    GetListForType(typeDropDownValueId, true);  //set to true as this is called when form loads
        //});
    </script>
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="margin: 10px 0px 10px">
            Add group
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("User changes", "Edit", "AppUsers", new { id = currentAppUserId }, "")</li>
            <li>@Html.ActionLink("Your groups", "Index", "Groups")</li>
            <li class="active">Add group</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <h4>Group details</h4>

                @Html.HiddenFor(model => model.scratchEntry)

                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "groupname" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*NOTE: The if statement to stop a field being changeable if it comes from the buttons and details are pre-loaded*@
                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @if (Model.scratchEntry)
                        {
                            @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control", @id = "typedropdown", onchange = "javascipt:GetListForType(this.value);" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @id = "typedropdown" } })
                        }
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.VisibilityLevel, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @Html.EnumDropDownListFor(model => model.VisibilityLevel, htmlAttributes: new { @class = "form-control", @id = "groupname" })
                        @Html.ValidationMessageFor(model => model.VisibilityLevel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.InviteLevel, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @Html.EnumDropDownListFor(model => model.InviteLevel, htmlAttributes: new { @class = "form-control", @id = "groupname" })
                        @Html.ValidationMessageFor(model => model.InviteLevel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">@Html.LabelFor(model => model.AcceptanceLevel, htmlAttributes: new { @class = "control-label" })</div>
                    <div class="col-md-8">
                        @Html.EnumDropDownListFor(model => model.AcceptanceLevel, htmlAttributes: new { @class = "form-control", @id = "groupname" })
                        @Html.ValidationMessageFor(model => model.AcceptanceLevel, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Add members</h4>
            <div id="usertable">
                <div class="table-responsive">
                    <table class="table table-hover" id="usertablelist">
                        <tr class="info">
                            <th>Select</th>
                            <th>Name</th>
                        </tr>
                        <tbody id="memberlist">
                            @{
                                Html.RenderPartial("AddGroupMembers", Model);
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-success" />
    </div>
}

Distributor/Views/Groups/Delete.cshtml
@model Distributor.Models.Group

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupOriginatorAppUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupOriginatorAppUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupOriginatorDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupOriginatorDateTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Distributor/Views/Groups/Details.cshtml
@model Distributor.Models.Group

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupOriginatorAppUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupOriginatorAppUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupOriginatorDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupOriginatorDateTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroupId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Distributor/Views/Groups/Index.cshtml
@using Distributor.Extenstions;

@model Distributor.ViewModels.GroupEditView

@{
    var currentAppUserId = User.Identity.GetAppUserId();
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/css/vendor")

    <script type="text/javascript">

        $(function () {
            //show/hide branch details to edit
            $('.showhidemembers').click(function () {
                $(this).closest('tbody').next('tbody').toggle();
            });
        });
    </script>
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="margin: 10px 0px 10px">
            Your groups
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("User changes", "Edit", "AppUsers", new { id = currentAppUserId }, "")</li>
            <li class="active">Your groups</li>
        </ol>
    </div>
</div>

<h4>Your groups</h4>
@if (Model.GroupListViewsCreatedByUser == null || Model.GroupListViewsCreatedByUser.Count == 0)
{
    <p>No groups to show</p>
}
else
{
    <div class="table-responsive">
        <table class="table table-hover">
            <tr class="info">
                <th></th>
                <th>Group name</th>
                <th>Owner</th>
                <th>Type</th>
                <th>Visibility</th>
                <th>Invite</th>
                <th>Acceptance</th>
            </tr>
            @for (int i = 0; i < Model.GroupListViewsCreatedByUser.Count; i++)
            {
                <tr>
                    <td><input style="width:70px" type="button" value="Members" class="btn btn-sm btn-primary btn-block showhidemembers" /></td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Group.Name)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].GroupOriginatorName)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Group.Type)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Group.VisibilityLevel)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Group.InviteLevel)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Group.AcceptanceLevel)</td>
                </tr>
                <tbody id="byuserbody" style="display:none">
                    <tr class="info">
                        <th></th>
                        <th>Members</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    @for (int z = 0; z < Model.GroupListViewsCreatedByUser[i].Members.Count; z++)
                    {
                        <tr>
                            <td></td>
                            <td></td>
                            <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Members[z].GroupMemberName)</td>
                            <td>@Html.DisplayFor(modelItem => Model.GroupListViewsCreatedByUser[i].Members[z].GroupMember.Type)</td>
                            <td></td>
                            <td></td>
                            <td></td>
                    </tr>
                    }
                </tbody>
            }
        </table>
    </div>
}

<h4>Groups you are included in</h4>
@if (Model.GroupListViewsRelevantToUser == null || Model.GroupListViewsRelevantToUser.Count == 0)
{
    <p>No groups to show</p>
}
else
{
    <div class="table-responsive">
        <table class="table table-hover">
            <tr class="info">
                <th></th>
                <th>Group name</th>
                <th>Owner</th>
                <th>Type</th>
                <th>Visibility</th>
                <th>Invite</th>
                <th>Acceptance</th>
            </tr>
            @for (int i = 0; i < Model.GroupListViewsRelevantToUser.Count; i++)
            {
                <tr>
                    <td><input style="width:70px" type="button" value="Members" class="btn btn-sm btn-primary btn-block showhidemembers" /></td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Group.Name)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].GroupOriginatorName)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Group.Type)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Group.VisibilityLevel)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Group.InviteLevel)</td>
                    <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Group.AcceptanceLevel)</td>
                </tr>
                <tbody id="byuserbody" style="display:none">
                    <tr class="info">
                        <th></th>
                        <th>Members</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    @for (int z = 0; z < Model.GroupListViewsRelevantToUser[i].Members.Count; z++)
                    {
                        <tr>
                            <td></td>
                            <td></td>
                            <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Members[z].GroupMemberName)</td>
                            <td>@Html.DisplayFor(modelItem => Model.GroupListViewsRelevantToUser[i].Members[z].GroupMember.Type)</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            }
        </table>
    </div>
}

<div class="form-group">
    <input type="button" value="Add group" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Groups", new { appUserId = currentAppUserId })'" />
</div>